export const ROUTES = {
  ROOT: "/",
  AUTH: "/auth",
  DASHBOARD: "/dashboard",
  ONBOARDING: "/onboard",
  HOME: "/home",
  CATEGORIES: "/categories",
  MENU: "/menu",
  MENU_MANAGEMENT: "/menu-management",
  CATEGORIES_MANAGEMENT: "/menu-management/categories-management",
  MENU_ITEM: "/menu-item",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER: "/order",
  ORDER_LIST: "/order-list",
  ORDER_DETAILS: "/order-details",
  TABLES: "/tables",
  KITCHEN: "/kitchen",
  NOT_FOUND: "/404",
  SETTINGS: "/settings",
};
