export const ROUTES = {
  ROOT: "/",
  AUTH: "/auth",
  DASHBOARD: "/dashboard",
  HOME: "/home",
  CATEGORIES: "/categories",
  MENU: "/menu",
  MENU_ITEM: "/menu-item",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER: "/order",
  ORDER_LIST: "/order-list",
  ORDER_DETAILS: "/order-details",
  NOT_FOUND: "/404",
};
