export const ENUMS = {
  taxName: [
    "Service charge",
    "Service tax",
    "VAT Alcoholic",
    "VAT Non-Alcoholic",
  ],
  tableStatus: ["Free", "Occupied"],
  orderStatus: ["New", "Ready", "Served", "Cancelled", "Billed"],
  menuItemType: ["Food", "Alcoholic Drink", "Non-Alcoholic Drink"],
  paymentStatus: ["Pending", "Paid", "Failed"],
  paymentMethod: ["Cash", "Card", "Online"],
  foodGroup: ["Veg", "Non-veg", "Vegan", "Egg"],
  subscriptionPlan: ["Free", "Bronze", "Silver", "Gold", "Diamond"],
  restroType: [
    "Fast food",
    "Casual dining",
    "Fine dining",
    "Cafe",
    "Restro and bar",
    "Bar",
    "Pub",
    "Food truck",
    "Buffet",
    "Food court",
    "Cloud kitchen",
  ],
  onboardingState: ["NEW", "TABLE", "MENU", "COMPLETED"],
};
