export const subscriptionPlans = [
  {
    name: "Free",
    description: "A premium-plus plan with all features for trial.",
    price: 1999,
    dailyCustomerLimit: 5000,
    monthlyCustomerLimit: 200000,
    menuCategoryLimit: 100,
    tableLimit: 10000,
    menuItemLimit: 5000,
  },
  {
    name: "Bronze",
    description: "A basic plan with extended features.",
    price: 599,
    dailyCustomerLimit: 30,
    monthlyCustomerLimit: 500,
    menuCategoryLimit: 5,
    tableLimit: 30,
    menuItemLimit: 30,
  },
  {
    name: "Silver",
    description: "A premium plan with advanced features.",
    price: 999,
    dailyCustomerLimit: 120,
    monthlyCustomerLimit: 2000,
    menuCategoryLimit: 15,
    tableLimit: 90,
    menuItemLimit: 100,
  },
  {
    name: "Gold",
    description: "A premium-plus plan with all features.",
    price: 1199,
    dailyCustomerLimit: 400,
    monthlyCustomerLimit: 7000,
    menuCategoryLimit: 50,
    tableLimit: 200,
    menuItemLimit: 300,
  },
  {
    name: "Diamond",
    description: "A premium-plus plan with all features.",
    price: 1999,
    dailyCustomerLimit: 1500,
    monthlyCustomerLimit: 20000,
    menuCategoryLimit: 100,
    tableLimit: 300,
    menuItemLimit: 500,
  },
];
