version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        TAG: ${TAG:-latest}
    container_name: pirha-server
    image: hiteshphd/phd-pirha:${TAG:-latest}
    ports:
      - "8080:8080" # Exposing server on port 8080
    networks:
      - myapp-network
    env_file:
      - ./server/.env

networks:
  myapp-network:
    driver: bridge
