version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        TAG: ${TAG:-latest}
    container_name: pirha-server
    image: hiteshphd/phd-pirha:${TAG:-latest}
    ports:
      - "8080:8080" # Exposing server on port 8080
    networks:
      - myapp-network
    env_file:
      - ./server/.env
  redis:
    image: "redis:alpine"
    container_name: pirha-redis
    ports:
      - "6379:6379" # Exposing Redis on port 6379
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
